name: "Nix Image"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build -L .#nixosConfigurations.iso.config.system.build.isoImage
    - name: Upload iso
      uses: actions/upload-artifact@v4
      with:
        path: result/iso/*.iso
        retention-days: 1
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      if: github.event_name == 'release' && github.event.action == 'created'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["result/iso/*.iso"]'
